using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;
using System.Diagnostics;
using System.Windows.Forms;
using emulatorLauncher.Tools;
using System.Text.RegularExpressions;
using System.Drawing;
using SharpDX.XInput;

namespace emulatorLauncher
{
    partial class FlycastGenerator
    {
        /// <summary>
        /// cf. https://github.com/flyinghead/flycast/blob/master/core/sdl/sdl.cpp
        /// </summary>
        private void UpdateSdlControllersWithHints()
        {
            var hints = new List<string>();

            if (hints.Count > 0)
            {
                SdlGameController.ReloadWithHints(string.Join(",", hints));
                Program.Controllers.ForEach(c => c.ResetSdlController());
            }
        }

        private void CreateControllerConfiguration(IniFile ini)
        {
            if (Program.SystemConfig.isOptSet("disableautocontrollers") && Program.SystemConfig["disableautocontrollers"] == "1")
                return;

            //UpdateSdlControllersWithHints();
            //int inputID = keycodeToHID[SDL.SDL_Keycode.SDLK_x];
        }

        static Dictionary<SDL.SDL_Keycode, int> keycodeToHID = new Dictionary<SDL.SDL_Keycode, int>()
        {
            { SDL.SDL_Keycode.SDLK_a, 4 },
            { SDL.SDL_Keycode.SDLK_b, 5 },
            { SDL.SDL_Keycode.SDLK_c, 6 },
            { SDL.SDL_Keycode.SDLK_d, 7 },
            { SDL.SDL_Keycode.SDLK_e, 8 },
            { SDL.SDL_Keycode.SDLK_f, 9 },
            { SDL.SDL_Keycode.SDLK_g, 10 },
            { SDL.SDL_Keycode.SDLK_h, 11 },
            { SDL.SDL_Keycode.SDLK_i, 12 },
            { SDL.SDL_Keycode.SDLK_j, 13 },
            { SDL.SDL_Keycode.SDLK_k, 14 },
            { SDL.SDL_Keycode.SDLK_l, 15 },
            { SDL.SDL_Keycode.SDLK_m, 16 },
            { SDL.SDL_Keycode.SDLK_n, 17 },
            { SDL.SDL_Keycode.SDLK_o, 18 },
            { SDL.SDL_Keycode.SDLK_p, 19 },
            { SDL.SDL_Keycode.SDLK_q, 20 },
            { SDL.SDL_Keycode.SDLK_r, 21 },
            { SDL.SDL_Keycode.SDLK_s, 22 },
            { SDL.SDL_Keycode.SDLK_t, 23 },
            { SDL.SDL_Keycode.SDLK_u, 24 },
            { SDL.SDL_Keycode.SDLK_v, 25 },
            { SDL.SDL_Keycode.SDLK_w, 26 },
            { SDL.SDL_Keycode.SDLK_x, 27 },
            { SDL.SDL_Keycode.SDLK_y, 28 },
            { SDL.SDL_Keycode.SDLK_z, 29 },
            { SDL.SDL_Keycode.SDLK_1, 30 },
            { SDL.SDL_Keycode.SDLK_2, 31 },
            { SDL.SDL_Keycode.SDLK_3, 32 },
            { SDL.SDL_Keycode.SDLK_4, 33 },
            { SDL.SDL_Keycode.SDLK_5, 34 },
            { SDL.SDL_Keycode.SDLK_6, 35 },
            { SDL.SDL_Keycode.SDLK_7, 36 },
            { SDL.SDL_Keycode.SDLK_8, 37 },
            { SDL.SDL_Keycode.SDLK_9, 38 },
            { SDL.SDL_Keycode.SDLK_0, 39 },
            { SDL.SDL_Keycode.SDLK_RETURN, 40 },
            { SDL.SDL_Keycode.SDLK_ESCAPE, 41 },
            { SDL.SDL_Keycode.SDLK_BACKSPACE, 42 },
            { SDL.SDL_Keycode.SDLK_TAB, 43 },
            { SDL.SDL_Keycode.SDLK_SPACE, 44 },
            { SDL.SDL_Keycode.SDLK_MINUS, 45 },
            { SDL.SDL_Keycode.SDLK_EQUALS, 46 },
            { SDL.SDL_Keycode.SDLK_LEFTBRACKET, 47 },
            { SDL.SDL_Keycode.SDLK_RIGHTBRACKET, 48 },
            { SDL.SDL_Keycode.SDLK_BACKSLASH, 49 },
            { SDL.SDL_Keycode.SDLK_SEMICOLON, 51 },
            { SDL.SDL_Keycode.SDLK_QUOTE, 52 },
            { SDL.SDL_Keycode.SDLK_BACKQUOTE, 53 },
            { SDL.SDL_Keycode.SDLK_COMMA, 54 },
            { SDL.SDL_Keycode.SDLK_PERIOD, 55 },
            { SDL.SDL_Keycode.SDLK_SLASH, 56 },
            { SDL.SDL_Keycode.SDLK_CAPSLOCK, 57 },
            { SDL.SDL_Keycode.SDLK_F1, 58 },
            { SDL.SDL_Keycode.SDLK_F2, 59 },
            { SDL.SDL_Keycode.SDLK_F3, 60 },
            { SDL.SDL_Keycode.SDLK_F4, 61 },
            { SDL.SDL_Keycode.SDLK_F5, 62 },
            { SDL.SDL_Keycode.SDLK_F6, 63 },
            { SDL.SDL_Keycode.SDLK_F7, 64 },
            { SDL.SDL_Keycode.SDLK_F8, 65 },
            { SDL.SDL_Keycode.SDLK_F9, 66 },
            { SDL.SDL_Keycode.SDLK_F10, 67 },
            { SDL.SDL_Keycode.SDLK_F11, 68 },
            { SDL.SDL_Keycode.SDLK_F12, 69 },
            { SDL.SDL_Keycode.SDLK_PRINTSCREEN, 70 },
            { SDL.SDL_Keycode.SDLK_SCROLLLOCK, 71 },
            { SDL.SDL_Keycode.SDLK_PAUSE, 72 },
            { SDL.SDL_Keycode.SDLK_INSERT, 73 },
            { SDL.SDL_Keycode.SDLK_HOME, 74 },
            { SDL.SDL_Keycode.SDLK_PAGEUP, 75 },
            { SDL.SDL_Keycode.SDLK_DELETE, 76 },
            { SDL.SDL_Keycode.SDLK_END, 77 },
            { SDL.SDL_Keycode.SDLK_PAGEDOWN, 78 },
            { SDL.SDL_Keycode.SDLK_RIGHT, 79 },
            { SDL.SDL_Keycode.SDLK_LEFT, 80 },
            { SDL.SDL_Keycode.SDLK_DOWN, 81 },
            { SDL.SDL_Keycode.SDLK_UP, 82 },
            { SDL.SDL_Keycode.SDLK_NUMLOCKCLEAR, 83 },
            { SDL.SDL_Keycode.SDLK_KP_DIVIDE, 84 },
            { SDL.SDL_Keycode.SDLK_KP_MULTIPLY, 85 },
            { SDL.SDL_Keycode.SDLK_KP_MINUS, 86 },
            { SDL.SDL_Keycode.SDLK_KP_PLUS, 87 },
            { SDL.SDL_Keycode.SDLK_KP_ENTER, 88 },
            { SDL.SDL_Keycode.SDLK_KP_1, 89 },
            { SDL.SDL_Keycode.SDLK_KP_2, 90 },
            { SDL.SDL_Keycode.SDLK_KP_3, 91 },
            { SDL.SDL_Keycode.SDLK_KP_4, 92 },
            { SDL.SDL_Keycode.SDLK_KP_5, 93 },
            { SDL.SDL_Keycode.SDLK_KP_6, 94 },
            { SDL.SDL_Keycode.SDLK_KP_7, 95 },
            { SDL.SDL_Keycode.SDLK_KP_8, 96 },
            { SDL.SDL_Keycode.SDLK_KP_9, 97 },
            { SDL.SDL_Keycode.SDLK_KP_0, 98 },
            { SDL.SDL_Keycode.SDLK_KP_PERIOD, 99 },
            { SDL.SDL_Keycode.SDLK_APPLICATION, 101 },
            { SDL.SDL_Keycode.SDLK_POWER, 102 },
            { SDL.SDL_Keycode.SDLK_KP_EQUALS, 103 },
            { SDL.SDL_Keycode.SDLK_F13, 104 },
            { SDL.SDL_Keycode.SDLK_F14, 105 },
            { SDL.SDL_Keycode.SDLK_F15, 106 },
            { SDL.SDL_Keycode.SDLK_F16, 107 },
            { SDL.SDL_Keycode.SDLK_F17, 108 },
            { SDL.SDL_Keycode.SDLK_F18, 109 },
            { SDL.SDL_Keycode.SDLK_F19, 110 },
            { SDL.SDL_Keycode.SDLK_F20, 111 },
            { SDL.SDL_Keycode.SDLK_F21, 112 },
            { SDL.SDL_Keycode.SDLK_F22, 113 },
            { SDL.SDL_Keycode.SDLK_F23, 114 },
            { SDL.SDL_Keycode.SDLK_F24, 115 },
            { SDL.SDL_Keycode.SDLK_EXECUTE, 116 },
            { SDL.SDL_Keycode.SDLK_HELP, 117 },
            { SDL.SDL_Keycode.SDLK_MENU, 118 },
            { SDL.SDL_Keycode.SDLK_SELECT, 119 },
            { SDL.SDL_Keycode.SDLK_STOP, 120 },
            { SDL.SDL_Keycode.SDLK_AGAIN, 121 },
            { SDL.SDL_Keycode.SDLK_UNDO, 122 },
            { SDL.SDL_Keycode.SDLK_CUT, 123 },
            { SDL.SDL_Keycode.SDLK_COPY, 124 },
            { SDL.SDL_Keycode.SDLK_PASTE, 125 },
            { SDL.SDL_Keycode.SDLK_FIND, 126 },
            { SDL.SDL_Keycode.SDLK_MUTE, 127 },
            { SDL.SDL_Keycode.SDLK_VOLUMEUP, 128 },
            { SDL.SDL_Keycode.SDLK_VOLUMEDOWN, 129 },
            { SDL.SDL_Keycode.SDLK_KP_COMMA, 133 },
            { SDL.SDL_Keycode.SDLK_KP_EQUALSAS400, 134 },
            { SDL.SDL_Keycode.SDLK_ALTERASE, 153 },
            { SDL.SDL_Keycode.SDLK_SYSREQ, 154 },
            { SDL.SDL_Keycode.SDLK_CANCEL, 155 },
            { SDL.SDL_Keycode.SDLK_CLEAR, 156 },
            { SDL.SDL_Keycode.SDLK_PRIOR, 157 },
            { SDL.SDL_Keycode.SDLK_RETURN2, 158 },
            { SDL.SDL_Keycode.SDLK_SEPARATOR, 159 },
            { SDL.SDL_Keycode.SDLK_OUT, 160 },
            { SDL.SDL_Keycode.SDLK_OPER, 161 },
            { SDL.SDL_Keycode.SDLK_CLEARAGAIN, 162 },
            { SDL.SDL_Keycode.SDLK_CRSEL, 163 },
            { SDL.SDL_Keycode.SDLK_EXSEL, 164 },
            { SDL.SDL_Keycode.SDLK_KP_00, 176 },
            { SDL.SDL_Keycode.SDLK_KP_000, 177 },
            { SDL.SDL_Keycode.SDLK_THOUSANDSSEPARATOR, 178 },
            { SDL.SDL_Keycode.SDLK_DECIMALSEPARATOR, 179 },
            { SDL.SDL_Keycode.SDLK_CURRENCYUNIT, 180 },
            { SDL.SDL_Keycode.SDLK_CURRENCYSUBUNIT, 181 },
            { SDL.SDL_Keycode.SDLK_KP_LEFTPAREN, 182 },
            { SDL.SDL_Keycode.SDLK_KP_RIGHTPAREN, 183 },
            { SDL.SDL_Keycode.SDLK_KP_LEFTBRACE, 184 },
            { SDL.SDL_Keycode.SDLK_KP_RIGHTBRACE, 185 },
            { SDL.SDL_Keycode.SDLK_KP_TAB, 186 },
            { SDL.SDL_Keycode.SDLK_KP_BACKSPACE, 187 },
            { SDL.SDL_Keycode.SDLK_KP_A, 188 },
            { SDL.SDL_Keycode.SDLK_KP_B, 189 },
            { SDL.SDL_Keycode.SDLK_KP_C, 190 },
            { SDL.SDL_Keycode.SDLK_KP_D, 191 },
            { SDL.SDL_Keycode.SDLK_KP_E, 192 },
            { SDL.SDL_Keycode.SDLK_KP_F, 193 },
            { SDL.SDL_Keycode.SDLK_KP_XOR, 194 },
            { SDL.SDL_Keycode.SDLK_KP_POWER, 195 },
            { SDL.SDL_Keycode.SDLK_KP_PERCENT, 196 },
            { SDL.SDL_Keycode.SDLK_KP_LESS, 197 },
            { SDL.SDL_Keycode.SDLK_KP_GREATER, 198 },
            { SDL.SDL_Keycode.SDLK_KP_AMPERSAND, 199 },
            { SDL.SDL_Keycode.SDLK_KP_DBLAMPERSAND, 200 },
            { SDL.SDL_Keycode.SDLK_KP_VERTICALBAR, 201 },
            { SDL.SDL_Keycode.SDLK_KP_DBLVERTICALBAR, 202 },
            { SDL.SDL_Keycode.SDLK_KP_COLON, 203 },
            { SDL.SDL_Keycode.SDLK_KP_HASH, 204 },
            { SDL.SDL_Keycode.SDLK_KP_SPACE, 205 },
            { SDL.SDL_Keycode.SDLK_KP_AT, 206 },
            { SDL.SDL_Keycode.SDLK_KP_EXCLAM, 207 },
            { SDL.SDL_Keycode.SDLK_KP_MEMSTORE, 208 },
            { SDL.SDL_Keycode.SDLK_KP_MEMRECALL, 209 },
            { SDL.SDL_Keycode.SDLK_KP_MEMCLEAR, 210 },
            { SDL.SDL_Keycode.SDLK_KP_MEMADD, 211 },
            { SDL.SDL_Keycode.SDLK_KP_MEMSUBTRACT, 212 },
            { SDL.SDL_Keycode.SDLK_KP_MEMMULTIPLY, 213 },
            { SDL.SDL_Keycode.SDLK_KP_MEMDIVIDE, 214 },
            { SDL.SDL_Keycode.SDLK_KP_PLUSMINUS, 215 },
            { SDL.SDL_Keycode.SDLK_KP_CLEAR, 216 },
            { SDL.SDL_Keycode.SDLK_KP_CLEARENTRY, 217 },
            { SDL.SDL_Keycode.SDLK_KP_BINARY, 218 },
            { SDL.SDL_Keycode.SDLK_KP_OCTAL, 219 },
            { SDL.SDL_Keycode.SDLK_KP_DECIMAL, 220 },
            { SDL.SDL_Keycode.SDLK_KP_HEXADECIMAL, 221 },
            { SDL.SDL_Keycode.SDLK_LCTRL, 224 },
            { SDL.SDL_Keycode.SDLK_LSHIFT, 225 },
            { SDL.SDL_Keycode.SDLK_LALT, 226 },
            { SDL.SDL_Keycode.SDLK_LGUI, 227 },
            { SDL.SDL_Keycode.SDLK_RCTRL, 228 },
            { SDL.SDL_Keycode.SDLK_RSHIFT, 229 },
            { SDL.SDL_Keycode.SDLK_RALT, 230 },
            { SDL.SDL_Keycode.SDLK_RGUI, 231 },
            { SDL.SDL_Keycode.SDLK_MODE, 257 },
            { SDL.SDL_Keycode.SDLK_AUDIONEXT, 258 },
            { SDL.SDL_Keycode.SDLK_AUDIOPREV, 259 },
            { SDL.SDL_Keycode.SDLK_AUDIOSTOP, 260 },
            { SDL.SDL_Keycode.SDLK_AUDIOPLAY, 261 },
            { SDL.SDL_Keycode.SDLK_AUDIOMUTE, 262 },
            { SDL.SDL_Keycode.SDLK_MEDIASELECT, 263 },
            { SDL.SDL_Keycode.SDLK_WWW, 264 },
            { SDL.SDL_Keycode.SDLK_MAIL, 265 },
            { SDL.SDL_Keycode.SDLK_CALCULATOR, 266 },
            { SDL.SDL_Keycode.SDLK_COMPUTER, 267 },
            { SDL.SDL_Keycode.SDLK_AC_SEARCH, 268 },
            { SDL.SDL_Keycode.SDLK_AC_HOME, 269 },
            { SDL.SDL_Keycode.SDLK_AC_BACK, 270 },
            { SDL.SDL_Keycode.SDLK_AC_FORWARD, 271 },
            { SDL.SDL_Keycode.SDLK_AC_STOP, 272 },
            { SDL.SDL_Keycode.SDLK_AC_REFRESH, 273 },
            { SDL.SDL_Keycode.SDLK_AC_BOOKMARKS, 274 },
            { SDL.SDL_Keycode.SDLK_BRIGHTNESSDOWN, 275 },
            { SDL.SDL_Keycode.SDLK_BRIGHTNESSUP, 276 },
            { SDL.SDL_Keycode.SDLK_DISPLAYSWITCH, 277 },
            { SDL.SDL_Keycode.SDLK_KBDILLUMTOGGLE, 278 },
            { SDL.SDL_Keycode.SDLK_KBDILLUMDOWN, 279 },
            { SDL.SDL_Keycode.SDLK_KBDILLUMUP, 280 },
            { SDL.SDL_Keycode.SDLK_EJECT, 281 },
            { SDL.SDL_Keycode.SDLK_SLEEP, 282 }
        };

        static Dictionary<SDL.SDL_Keycode, SDL.SDL_Keycode> azertyLayoutMapping = new Dictionary<SDL.SDL_Keycode, SDL.SDL_Keycode>()
        {
            { SDL.SDL_Keycode.SDLK_a, SDL.SDL_Keycode.SDLK_q },
            { SDL.SDL_Keycode.SDLK_q, SDL.SDL_Keycode.SDLK_a },
            { SDL.SDL_Keycode.SDLK_z, SDL.SDL_Keycode.SDLK_w },
            { SDL.SDL_Keycode.SDLK_w, SDL.SDL_Keycode.SDLK_z },
            { SDL.SDL_Keycode.SDLK_m, SDL.SDL_Keycode.SDLK_COMMA },
            { SDL.SDL_Keycode.SDLK_SEMICOLON, SDL.SDL_Keycode.SDLK_m },
            { SDL.SDL_Keycode.SDLK_COMMA, SDL.SDL_Keycode.SDLK_SEMICOLON },
            { SDL.SDL_Keycode.SDLK_PERIOD, SDL.SDL_Keycode.SDLK_KP_COLON },
            { SDL.SDL_Keycode.SDLK_SLASH, SDL.SDL_Keycode.SDLK_EXCLAIM },
        };
    }
}
