using EmulatorLauncher.Common;
using EmulatorLauncher.Common.EmulationStation;
using EmulatorLauncher.Common.Joysticks;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace EmulatorLauncher
{
    partial class JZintvGenerator : Generator
    {
        private void ConfigureControllers(List<string> commandArray, string path)
        {
            if (Program.SystemConfig.isOptSet("disableautocontrollers") && Program.SystemConfig["disableautocontrollers"] == "1")
            {
                SimpleLogger.Instance.Info("[INFO] Controller autoconfiguration disabled.");
                return;
            }

            if (Program.Controllers.Where(c => !c.IsKeyboard).Count() == 0)
            {
                SimpleLogger.Instance.Info("[INFO] No controller connected, skipping controller configuration.");
                return;
            }

            SimpleLogger.Instance.Info("[INFO] Creating controller configuration for jzintv");

            string configFile = Path.Combine(Path.GetDirectoryName(path), "hackfile_retrobat.cfg");
            List<string> lines = new List<string>();

            try
            {
                // Header
                lines.Add("; RetroBat hackfile for jzintv, generated on " + DateTime.Now.ToString("dd/MM/yy - HH:mm"));
                lines.Add(string.Empty);

                if (Program.Controllers.Count > 1)
                {
                    var c1 = Program.Controllers.FirstOrDefault(c => c.PlayerIndex == 1);
                    var c2 = Program.Controllers.FirstOrDefault(c => c.PlayerIndex == 2);
                }
                else if (Program.Controllers.Count == 1)
                {
                    var c1 = Program.Controllers.FirstOrDefault(c => c.PlayerIndex == 1);
                }

                File.WriteAllLines(configFile, new string[] { "# RetroBat hackfile for jzintv", "# Generated by EmulatorLauncher", "" });
            }
            catch { }
            
            return;
        }

        private bool GetButton(Controller c, InputKey key, out string buttonMap)
        {
            buttonMap = "";
            return false;
        }
    }
}
