//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace batocera_store.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("batocera_store.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;packages&gt;
        ///  &lt;package&gt;
        ///    &lt;name&gt;bezels-default-glazed&lt;/name&gt;
        ///    &lt;repository&gt;batocera&lt;/repository&gt;
        ///    &lt;available_version&gt;1.0.0-2&lt;/available_version&gt;
        ///    &lt;description&gt;Batocera bezels with a CRT effect&lt;/description&gt;
        ///    &lt;url&gt;https://github.com/batocera-linux/batocera-bezel&lt;/url&gt;
        ///    &lt;packager&gt;lbrpdx&lt;/packager&gt;
        ///    &lt;download_size&gt;0&lt;/download_size&gt;
        ///    &lt;installed_size&gt;0&lt;/installed_size&gt;
        ///    &lt;status&gt;none&lt;/status&gt;
        ///  &lt;/package&gt;
        ///  &lt;package&gt;
        ///    &lt;name&gt;gb-into-the-blue&lt;/name&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string batocera_store {
            get {
                return ResourceManager.GetString("batocera_store", resourceCulture);
            }
        }
    }
}
