//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emulatorLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("emulatorLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Bezel {
            get {
                object obj = ResourceManager.GetObject("Bezel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400/600XL/800 (48K) (OS B)
        ///800XL/1200XL/XEGS (64K)
        ///130XE (128K)
        ///Modern XL/XE (320K CS)
        ///Modern XL/XE (576K)
        ///Modern XL/XE (1088K)
        ///normal2x
        ///normal3x
        ///advmame2x
        ///advmame3x
        ///advinterp2x
        ///advinterp3x
        ///hq2x
        ///hq3x
        ///2xai
        ///super2xai
        ///supereagle
        ///tv2x
        ///tv3x
        ///rgb2x
        ///rgb3x
        ///scan2x
        ///scan3x
        ///JINC2
        ///xBR
        ///default
        ///asqrealc
        ///nintendo-vc
        ///rgb
        ///yuv-v3
        ///unsaturated-final
        ///sony-cxa2025as-us
        ///pal
        ///bmf-final2
        ///bmf-final3
        ///smooth-fbx
        ///composite-direct-fbx
        ///pvm-style-d93-fbx
        ///ntsc-hardware-fbx
        ///nes-classic-fbx-fs
        ///nescap
        ///wav [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string blacklisted_words {
            get {
                return ResourceManager.GetString("blacklisted_words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] configgen_defaults {
            get {
                object obj = ResourceManager.GetObject("configgen_defaults", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The core &apos;{0}&apos; is not installed.
        ///Install now ?.
        /// </summary>
        internal static string CoreNotInstalled {
            get {
                return ResourceManager.GetString("CoreNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0}.
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] eeprom {
            get {
                object obj = ResourceManager.GetObject("eeprom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The emulator &apos;{0}&apos; is not installed.
        ///Install now ?.
        /// </summary>
        internal static string EmulatorNotInstalled {
            get {
                return ResourceManager.GetString("EmulatorNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured :
        ///{0}.
        /// </summary>
        internal static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning : Future Pinball requires developper mode enabled in Windows settings.
        /// </summary>
        internal static string FPinballDeveloperMode {
            get {
                return ResourceManager.GetString("FPinballDeveloperMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing.....
        /// </summary>
        internal static string Installing {
            get {
                return ResourceManager.GetString("Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to keep the uncompressed game for further use ?.
        /// </summary>
        internal static string KeepUncompressedFile {
            get {
                return ResourceManager.GetString("KeepUncompressedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for updates....
        /// </summary>
        internal static string LookingForUpdates {
            get {
                return ResourceManager.GetString("LookingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #
        ///# CORE CONFIGURATION OPTIONS
        ///#
        ///readconfig                1
        ///writeconfig               0
        ///
        ///#
        ///# CORE SEARCH PATH OPTIONS
        ///#
        ///homepath                  .
        ///rompath                   roms
        ///hashpath                  hash
        ///samplepath                samples
        ///artpath                   artwork
        ///ctrlrpath                 ctrlr
        ///inipath                   .;ini;ini/presets
        ///fontpath                  .
        ///cheatpath                 cheat
        ///crosshairpath             crosshair
        ///pluginspath               plugins
        ///languag [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mame {
            get {
                return ResourceManager.GetString("mame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] mamecrcs_xml_gz {
            get {
                object obj = ResourceManager.GetObject("mamecrcs_xml_gz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReShade {
            get {
                object obj = ResourceManager.GetObject("ReShade", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [D3D9]
        ///DepthCopyAtClearIndex=0
        ///DepthCopyBeforeClears=0
        ///DisableINTZ=0
        ///UseAspectRatioHeuristics=1
        ///
        ///[OPENGL]
        ///ForceMainDepthBuffer=0
        ///UseAspectRatioHeuristics=1
        ///
        ///[GENERAL]
        ///EffectSearchPaths=.\reshade-shaders\Shaders
        ///PerformanceMode=0
        ///PreprocessorDefinitions=
        ///PresetPath=.\ReShadePreset.ini
        ///PresetFiles=.\ReShadePreset.ini
        ///PresetTransitionDelay=1000
        ///SkipLoadingDisabledEffects=0
        ///TextureSearchPaths=.\reshade-shaders\Textures
        ///TutorialProgress=4
        ///
        ///[INPUT]
        ///ForceShortcutModifiers=1
        ///InputProcessing=2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReShadeIni {
            get {
                return ResourceManager.GetString("ReShadeIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReShadeUI {
            get {
                object obj = ResourceManager.GetObject("ReShadeUI", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap retrobat {
            get {
                object obj = ResourceManager.GetObject("retrobat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompressing {0}.
        /// </summary>
        internal static string UnCompressing {
            get {
                return ResourceManager.GetString("UnCompressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is available for {0} :
        ///Update version : {1}
        ///Installed version : {2}
        ///Install now ?.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating {0}.
        /// </summary>
        internal static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] xbox_hdd_qcow2 {
            get {
                object obj = ResourceManager.GetObject("xbox_hdd_qcow2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
