//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmulatorLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmulatorLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back to game.
        /// </summary>
        internal static string BackToGame {
            get {
                return ResourceManager.GetString("BackToGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] Bezel {
            get {
                object obj = ResourceManager.GetObject("Bezel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 400/600XL/800 (48K) (OS B)
        ///800XL/1200XL/XEGS (64K)
        ///130XE (128K)
        ///Modern XL/XE (320K CS)
        ///Modern XL/XE (576K)
        ///Modern XL/XE (1088K)
        ///normal2x
        ///normal3x
        ///advmame2x
        ///advmame3x
        ///advinterp2x
        ///advinterp3x
        ///hq2x
        ///hq3x
        ///2xai
        ///super2xai
        ///supereagle
        ///tv2x
        ///tv3x
        ///rgb2x
        ///rgb3x
        ///scan2x
        ///scan3x
        ///JINC2
        ///xBR
        ///default
        ///asqrealc
        ///nintendo-vc
        ///rgb
        ///yuv-v3
        ///unsaturated-final
        ///sony-cxa2025as-us
        ///pal
        ///bmf-final2
        ///bmf-final3
        ///smooth-fbx
        ///composite-direct-fbx
        ///pvm-style-d93-fbx
        ///ntsc-hardware-fbx
        ///nes-classic-fbx-fs
        ///nescap
        ///wav [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string blacklisted_words {
            get {
                return ResourceManager.GetString("blacklisted_words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] configgen_defaults {
            get {
                object obj = ResourceManager.GetObject("configgen_defaults", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The core &apos;{0}&apos; is not installed.
        ///Install now ?.
        /// </summary>
        internal static string CoreNotInstalled {
            get {
                return ResourceManager.GetString("CoreNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Downloading {0}.
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] eeprom {
            get {
                object obj = ResourceManager.GetObject("eeprom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The emulator &apos;{0}&apos; is not installed.
        ///Install now ?.
        /// </summary>
        internal static string EmulatorNotInstalled {
            get {
                return ResourceManager.GetString("EmulatorNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occured :
        ///{0}.
        /// </summary>
        internal static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning : Future Pinball requires developper mode enabled in Windows settings.
        /// </summary>
        internal static string FPinballDeveloperMode {
            get {
                return ResourceManager.GetString("FPinballDeveloperMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] hidtodinput {
            get {
                object obj = ResourceManager.GetObject("hidtodinput", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Installing.....
        /// </summary>
        internal static string Installing {
            get {
                return ResourceManager.GetString("Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to keep the uncompressed game for further use ?.
        /// </summary>
        internal static string KeepUncompressedFile {
            get {
                return ResourceManager.GetString("KeepUncompressedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kill emulator.
        /// </summary>
        internal static string KillEmulator {
            get {
                return ResourceManager.GetString("KillEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] libretrocoreguns {
            get {
                object obj = ResourceManager.GetObject("libretrocoreguns", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Looking for updates....
        /// </summary>
        internal static string LookingForUpdates {
            get {
                return ResourceManager.GetString("LookingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #
        ///# CORE CONFIGURATION OPTIONS
        ///#
        ///readconfig                1
        ///writeconfig               0
        ///
        ///#
        ///# CORE SEARCH PATH OPTIONS
        ///#
        ///homepath                  .
        ///rompath                   roms
        ///hashpath                  hash
        ///samplepath                samples
        ///artpath                   artwork
        ///ctrlrpath                 ctrlr
        ///inipath                   .;ini;ini/presets
        ///fontpath                  .
        ///cheatpath                 cheat
        ///crosshairpath             crosshair
        ///pluginspath               plugins
        ///languag [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string mame {
            get {
                return ResourceManager.GetString("mame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] mamecrcs_xml_gz {
            get {
                object obj = ResourceManager.GetObject("mamecrcs_xml_gz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manual.
        /// </summary>
        internal static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Map.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] ReShade {
            get {
                object obj = ResourceManager.GetObject("ReShade", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [D3D9]
        ///DepthCopyAtClearIndex=0
        ///DepthCopyBeforeClears=0
        ///DisableINTZ=0
        ///UseAspectRatioHeuristics=1
        ///
        ///[OPENGL]
        ///ForceMainDepthBuffer=0
        ///UseAspectRatioHeuristics=1
        ///
        ///[GENERAL]
        ///EffectSearchPaths=.\reshade-shaders\Shaders
        ///PerformanceMode=0
        ///PreprocessorDefinitions=
        ///PresetPath=.\ReShadePreset.ini
        ///PresetFiles=.\ReShadePreset.ini
        ///PresetTransitionDelay=1000
        ///SkipLoadingDisabledEffects=0
        ///TextureSearchPaths=.\reshade-shaders\Textures
        ///TutorialProgress=4
        ///
        ///[INPUT]
        ///ForceShortcutModifiers=1
        ///InputProcessing=2 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string ReShadeIni {
            get {
                return ResourceManager.GetString("ReShadeIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] reshader_x64_gz {
            get {
                object obj = ResourceManager.GetObject("reshader_x64_gz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] reshader_x86_gz {
            get {
                object obj = ResourceManager.GetObject("reshader_x86_gz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] ReShadeUI {
            get {
                object obj = ResourceManager.GetObject("ReShadeUI", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap retrobat {
            get {
                object obj = ResourceManager.GetObject("retrobat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tatoo.
        /// </summary>
        internal static string Tatoo {
            get {
                return ResourceManager.GetString("Tatoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decompressing {0}.
        /// </summary>
        internal static string UnCompressing {
            get {
                return ResourceManager.GetString("UnCompressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An update is available for {0} :
        ///Update version : {1}
        ///Installed version : {2}
        ///Install now ?.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Updating {0}.
        /// </summary>
        internal static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] wheelmapping {
            get {
                object obj = ResourceManager.GetObject("wheelmapping", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] wheelsdlmapping {
            get {
                object obj = ResourceManager.GetObject("wheelsdlmapping", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] xbox_hdd_qcow2 {
            get {
                object obj = ResourceManager.GetObject("xbox_hdd_qcow2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
